export default {
    projectCreatePopup: '#create-project-popup',
    projectAddColumnPopup: '#add-column-popup',
    projectSearch: '.search',
    projectNamesList: '.tab-header',
    projectTab: '.tab-head',
    projectAddBtn: '.tab-head-add',
    projectContent: '.project-content',
    projectColumn: '.column',
    projectTask: '.task',
    projectAddTask: '.add-task',
    projectAddTaskBtn: '.add-task--js',
    projectNewAddTaskBtn: '.add-new-task--js',
    projectDeleteTask: '.delete-task--js',
    projectNewDeleteTask: '.delete-new-task--js',
    projectTaskPriority: '.set-priority--js',
    projectAddLabel: '.add-label--js',
    projectAddLabelInput: '.add-label-input',
    projectNewTaskPriority: '.set-new-priority--js',
    projectSetTaskTime: '.set-time--js',
    projectAddTimeInput: '.add-time-input',
    projectTaskLabel: '.label',
    projectChangeTaskState: '.change-status--js',
    projectEditTask: '.edit--js',
    projectSaveTask: '.save-task--js',
    projectTimerStart: '.start--js',
    projectNewColumn: '.add-new-column',
    projectAddColumnBtn: '.add-column--js',
    projectDeleteColumnBtn: '.delete-column-btn--js',
    projectCreateColumnBtn: '#create-column--js',
    projectColumnName: '#column-name',
    projectNewTask: '.new-task',
    projectNameInsert: '.insert-project--js',
    projectName: '#project-name',
    projectDescription: '#project-description',
    projectCreateBtn : '#create-project--js'
}